### ISSUE TITLE
Debug files in its own repository

### ISSUE THREAD

**Issue by michaelnordmeyer** [wfjm/wfjm.github.io#1]
I discovered the debug files which display infos about Github pages state, settings, versions etc. Well done!

I'd like to use those on my site, but it's unnecessary hard to use them as they are located in your website's repository. If they would live in its own repo, it's much easier to fork and integrate this repo in my own as a submodule [like mentioned here](https://stackoverflow.com/questions/2140985/how-to-set-up-a-git-project-to-use-an-external-repo-submodule). Then all your changes will eventually show up in my own repo.

What you you think?

**Comment by wfjm** [comment]
Hallo,

thanks for the interest and the suggestion. I'm o a longer trip and can't have a detailed look at it. But two questions come immediately to my mind:

1. are submodules supported for github.io pages ? For normal projects it's clear how to use submodules. But for github.io pages the whole git fetch/update is done automatically when the static HTLM pages are generated after a commit

2. How to handle css, templates ect ?

Any hints or suggestions are very welcome.

**Comment by wfjm** [comment]
Hi @michaelnordmeyer,

I verified that submodules are supported for GitHub Pages, see [this docu page](https://help.github.com/articles/using-submodules-with-pages/). That answers the first question.

A submodule always lives in its own subdirectory structure. The debug pages make use of the page definitions in the `debug` directory, but also use some includes in `_include`, and of course the CSS in the `css` directory. So it's not straight forward to factor the debug pages out into a submodule. Any idea of how to handle this ??

**Comment by wfjm** [comment]
Hi @michaelnordmeyer,
I close the issue because no proposal for a concrete implementation was send. If somebody sends this I'll certainly review it and do my best to include it.
